[build]
  publish = "."
  command = "# no build command needed"

[dev]
  framework = "#static"
  targetPort = 8888

[[redirects]]
  from = "/"
  to = "/Get-iOS-UDID/index.html"
  status = 200

[[redirects]]
  from = "/get-ios-udid/*"
  to = "/Get-iOS-UDID/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/Get-iOS-UDID/*"
  to = "/Get-iOS-UDID/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200